### ISSUE TITLE
Notification is sent multiple times

### ISSUE THREAD

**Issue by abdoolly** [Alymosul/exponent-server-sdk-php#18]
when i try to send notification to a device it get sent multiple times at the same time

**Comment by Alymosul** [comment]
Can you share your code? I think you're subscribing the device more than once?

**Comment by abdoolly** [comment]
Here the code I used I just made a route which calls this function just one time and I find the notification sent multiple times.

Am so sorry for my late response.
Thanks in advance.
```
<?php

namespace App\Services\Utilities;

use App\Client;
use \ExponentPhpSDK\Expo;

class PushNotificationUtil
{
    public function sendPushNotification(Client $user, $data)
    {
        $details = [$user->device_token];

        $expo = Expo::normalSetup();

        // Subscribe the recipient to the server
        // $expo->subscribe($detais[0], $detais[1]);
        // Build the notification data
        $notification = [
            'to' => $user->device_token,
            'sound' => 'default',
            'body' => 'Hello World!',
            'data' => json_encode(['someData' => 'goes here'])
        ];

        // Notify an interest with a notification
        $expo->notify($details, $notification);
    }
}
```

**Comment by Alymosul** [comment]
Your code seems wrong to me... your notification data should not contain 'to'. Also $expo->subscribe($details[0], $details[1]); should produce a fatal error because the $details contain only 1 element. I think you should update to the latest version because it will check if the given token is already registered

**Comment by joelabeyta** [comment]
I'm having a similar issue. Each new notification sends one more notification. So after 5 tests, the recipient gets 5 notifications.

Here is my implementation:

`	require_once __DIR__.'/vendor/autoload.php';

	// call back function for rest api endpoint
	function cw_expo_push_notif($title = '', $msg = '', $team = '', $dev = false) {
		$cw_notif = new CW_Simple_Notifications;
		$send = $cw_notif->send_notif($title, $msg, $team, $dev);
	}

	class CW_Simple_Notifications {
		private function get_recipients($team, $os) {
			global $wpdb;
			$table_name = $wpdb->prefix . 'push_device_registry';

			if(!empty($team)) {
				// get recipients who are interested in this team
				$recipients = $wpdb->get_results("select * from `" . $table_name . "` where `os` like '%".$os."%' and `notifications` LIKE '%".$team."%' and `regid` != '' and `uuid` != ''", ARRAY_A);
			} else {
				// general notification, no team selected
				$recipients = $wpdb->get_results("select * from `" . $table_name . "` where `os` like '%".$os."%' and `regid` != '' and `uuid` != ''", ARRAY_A);
			}

			return $recipients;
		}

		public function send_notif($title, $msg, $team, $dev) {
			// get all interested recipients
			$recipients = $this->get_recipients($team, 'ios');

			// dev options
			if($dev) {
				$returns = array($title, $msg, $team, $recipients);
			} else {
				$returns = '';
			}

			if(!empty($recipients)) {
				// You can quickly bootup an expo instance
				$expo = \ExponentPhpSDK\Expo::normalSetup();

				foreach ($recipients as $recipient) {
					$token = $recipient['regid'];
					$uuid = $recipient['uuid'];

					$notification = '';

					$notification = ['title' => $title, 'body' => $msg];

					// Subscribe the recipient to the server
					$expo->subscribe($uuid, $token);

					// Notify an interest with a notification
					$expo->notify($uuid, $notification);
				}
			}

			return $returns;
		}
	}`

I'm not sure if this is an issue or just something I'm missing.

**Comment by joelabeyta** [comment]
I'm having a similar issue. Each new test sends another copy of the notification. So after 5 tests, the recipients receive 5 copies of the notification. 

Here is my implementation: 

`<?php
	require_once __DIR__.'/vendor/autoload.php';

	// call back function for rest api endpoint
	function cw_expo_push_notif($title = '', $msg = '', $team = '', $dev = false) {
		$cw_notif = new CW_Simple_Notifications;
		$send = $cw_notif->send_notif($title, $msg, $team, $dev);
	}

	class CW_Simple_Notifications {
		private function get_recipients($team, $os) {
			global $wpdb;
			$table_name = $wpdb->prefix . 'push_device_registry';

			if(!empty($team)) {
				// get recipients who are interested in this team
				$recipients = $wpdb->get_results("select * from `" . $table_name . "` where `os` like '%".$os."%' and `notifications` LIKE '%".$team."%' and `regid` != '' and `uuid` != ''", ARRAY_A);
			} else {
				// general notification, no team selected
				$recipients = $wpdb->get_results("select * from `" . $table_name . "` where `os` like '%".$os."%' and `regid` != '' and `uuid` != ''", ARRAY_A);
			}

			return $recipients;
		}

		public function send_notif($title, $msg, $team, $dev) {
			// get all interested recipients
			$recipients = $this->get_recipients($team, 'ios');

			// dev options
			if($dev) {
				$returns = array($title, $msg, $team, $recipients);
			} else {
				$returns = '';
			}

			if(!empty($recipients)) {
				// You can quickly bootup an expo instance
				$expo = \ExponentPhpSDK\Expo::normalSetup();

				foreach ($recipients as $recipient) {
					$token = $recipient['regid'];
					$uuid = $recipient['uuid'];

					$notification = '';

					$notification = ['title' => $title, 'body' => $msg];

					// Subscribe the recipient to the server
					$expo->subscribe($uuid, $token);

					// Notify an interest with a notification
					$expo->notify($uuid, $notification);
				}
			}

			return $returns;
		}
	}`

I'm not sure what I'm missing.

**Comment by joelabeyta** [comment]
I found out part of the issue. It's saving the token multiple times in the tokens.json file.

Maybe the readme could use a little more information. I'm confused what the the 'unique identifier' should be in the $interestDetails in your example. Can it be anything or is it looking for something in particular? I'm trying to use the UUID which would be unique to each device.

**Comment by joelabeyta** [comment]
I managed to solve the issue by bypassing the entire subscription part since I'm managing that in a separate database. I added this function to Expo.php:

`
    public function no_sub_notify($interests, $token, array $data, $debug = false)
    {
        $postData = [];

        if (is_string($interests)) {
            $interests = [$interests];
        }

        if (count($interests) == 0) {
            throw new ExpoException('Interests array must not be empty.');
        }

        $postData[] = $data + ['to' => $token];

        $ch = $this->prepareCurl();

        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postData));

        $response = $this->executeCurl($ch);

        // If the notification failed completely, throw an exception with the details
        if (!$debug && $this->failedCompletely($response, $interests)) {
            throw ExpoException::failedCompletelyException($response);
        }

        return $response;
    }
`

 and run the notifs this way: $expo->no_sub_notify($uuid, $token, $notification);

**Comment by Alymosul** [comment]
It seems that the problem is in subscribing the interests with the same token several times leading to duplicated tokens which is solved in the latest version (you can use the dev version also), I'll implement a test suite for the package to make sure that such bug won't pass to releases again.

**Comment by abdoolly** [comment]
> Your code seems wrong to me... your notification data should not contain 'to'. Also $expo->subscribe($details[0], $details[1]); should produce a fatal error because the $details contain only 1 element. I think you should update to the latest version because it will check if the given token is already registered

**Comment by abdoolly** [comment]
Thanks for your support and sorry for my late response @Alymosul

**Comment by Ahmed-Imam** [comment]
I am still facing the problem, it sends multiple notifications at once, my code is as follow
```
<?php
   require_once('./vendor/autoload.php');
   require_once('./includes_/mysql_functions.php');


 $msg = 'Aloo';
$key = "ExponentPushToken[OcavxbB6AsB5wr_Ep7Fxhn]";
$title = "title";
  
  try{
      $expo = \ExponentPhpSDK\Expo::normalSetup();
  // Build the notification data
  $notification = ['to' => $key,'title' => $title,'body' => $msg];
  // Notify an interest with a notification
 $expo->notify('https://exp.host/--/api/v2/push/send',$notification);
  	
  $status = 'success';
}catch(Exception $e){
	echo $e;
}
  echo $status;
  ?>
```
